version: '3'
services:
  app:
    image: gazin-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbgazin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
